const BAD_REQUEST_ERROR_CODE = 400;
const NONEXISTENT_ERROR_CODE = 404;
const DEFAULT_ERROR_CODE = 500;
const UNAUTHORIZED_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;

module.exports = {
  BAD_REQUEST_ERROR_CODE,
  NONEXISTENT_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
};
